// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shogmmpqpwkljdlmmcbs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNob2dtbXBxcHdrbGpkbG1tY2JzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MDg2OTQsImV4cCI6MjA3NDA4NDY5NH0.Mf3Ltw_1s1zXVnZFzzLCFKqib_NQMiWge9welYUhQKs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});